### ISSUE TITLE
imageoffset and imagesize do not work

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/BlockOut#12]
I am working on a resource pack for minecolonies whereby the minecolonies textures would inherit from whatever texture pack the player has installed. This is not working, though, because the imageoffset and imagesize do not work.

Expected behavior:
imageoffset="0px 0px" (pixel-based)
imagesize="100px 20px" (pixel-based)

imageoffset="0 0" (pixel-based)
imagesize="100 20" (pixel-based)

imageoffset="0% 0%" (percent-based on image total width/height)
imagesize="19.53125% 3.90625%" (percent-based on image total width/height)

Example:
```xml
<buttonimage id="inventory"
align="BOTTOM_MIDDLE" size="86 17" pos="0 13"
source="minecraft:textures/gui/widgets.png"
imageoffset="0% 25.78125%"
imagesize="77.9296875% 7.6171875%"
label="$(container.inventory)" textcolor="black"/>
```

----
The ideal solution would be to use the % values so that the same xml would support any texture pack regardless of resolution.

The image, whether by offset/size or a full image should be resized/scaled to fit within the size specified by the container and not truncated.

**Comment by marchermans** [comment]
This is something we are currently not going to fix.
I am currently working on extracting blockout into a seperate library were this is taken care off. It will autoscale the UI 100% of the time, regardless of UI size, Image or any other factor.

Sorry for the inconvenience.
Orion

**Comment by marchermans** [comment]
Oh you are commenting on BlockOut XD

**Comment by marchermans** [comment]
Ehm this BlockOut is not yet in use by Minecolonies. However It will be shortly, as stated this new version will support these kinds of things automatically.
